# This is a config file for `coq-config`.
# https://github.com/vzaliva/coq-config

opam:
  switch: cam
  compiler: 4.12.0

repositories:
  - name: coq-released
    address: https://coq.inria.fr/opam/released

dependencies:
  - coq.8.13.2
  - coq-bbv
#  - coq-mathcomp-algebra

# There is a package `coq-bits` in OPAM but it currently
# does not support Coq-8.13. There is a pull request pending
# to fix that. Meanwhile we will use this patched copy instead.
# It is to be replaced by `coq-bits` dependency once the PR
# https://github.com/coq-community/bits/pull/14 is merged.
#extra-deps:
#  - git: git@github.com:vzaliva/bits.git
#    recurse-submodules: no
#    commit: coq813
#    path: lib/bits
